### ISSUE TITLE
Unable to make weapons make damage.

### ISSUE THREAD

**Issue by xs4u** [IITPP-Roblox/Projectile-Replication#3]
We (me & braddy) can't make the weapons deal **ANY** damage.
```lua
    OnHitServer = function(Part, Position, Projectile)
		print("Projectile hit "..tostring(Part).." at position "..tostring(Position).." using projectile "..tostring(Projectile).." on the server")
		if Part.Parent:FindFirstChildOfClass("Humanoid") then Part.Parent:FindFirstChildOfClass("Humanoid"):TakeDamage(15) print("humanoid!") else print("no humanoid") end
    end,
```
This code doesn't even do the "no humanoid" print for some reason.

**Comment by TheNexusAvenger** [comment]
From that code snippet, there is nothing obviously wrong. `OnHitServer` is the correct name to use in the preset. You are firing projectiles on the server, right?

**Comment by xs4u** [comment]
I fire them using standard weapon.

**Comment by xs4u** [comment]
Is it supposed to be OnHitClient in that case?

**Comment by TheNexusAvenger** [comment]
> I fire them using standard weapon.

Then I don't know what is going on. `OnHitServer` works for both Innovation Inc Thermal Power Plant and Innovation Security Training Facility

> Is it supposed to be OnHitClient in that case?

No. `OnHitClient` is ran on the client. Damaging the `Humanoid` must be done on the server.

**Comment by xs4u** [comment]
I see, that's weird

**Comment by TheNexusAvenger** [comment]
Closing assuming this is not an issue on our end. Please re-open with more information on how to reproduce this if this is still a problem.

**Comment by xs4u** [comment]
I mean the issue seems to also not be on our side, the server doesn't print anything at all
