### ISSUE TITLE
Line 12 in ServerWeaponSetup preventing script from functioning

### ISSUE THREAD

**Issue by CreativeConnYT** [IITPP-Roblox/Projectile-Replication#5]
Line 12 is erroring out the script every time I try to playtest the game. 

(Line 12, ServerWeaponSetup, located in ServerScriptService)

```lua
local ProjectileReplication = require(ReplicatedStorage:WaitForChild("ProjectileReplication")) :: any
```

**Comment by TheNexusAvenger** [comment]
What error are you getting?

**Comment by CreativeConnYT** [comment]
This is what I'm getting in Output.

![image](https://github.com/IITPP-Roblox/Projectile-Replication/assets/141884392/0e23b014-b3ca-41a1-8582-e920309c4295)

**Comment by TheNexusAvenger** [comment]
Did you make sure to clone the submodules as well (`git submodule update --init --recursive`)?
